### ISSUE TITLE
VS Code plugin system disabled

### ISSUE THREAD

**Issue by EvanWeeks** [Armitxes/VSCode_SQF#1]
This is not your fault, of course, but the team at microsoft have apparently disabled the plugin system entirely because they "weren't happy with it."

One wonders when they'll decide to re-add that particular feature. :/

**Comment by Armitxes** [comment]
The plugin System is still there, they only moved the plugin Folder to "C:\Program Files (x86)\Microsoft VS Code\resources\app\plugins\"

Create the "vs.language.sqf" in the plugin folder and unzip the Content of the master.zip (SQF Plugin) in there. Should fix it :)

https://forums.bistudio.com/topic/182917-vs-code-sqf-visual-studio-code-sqf-language-release-arma-3-arma-2/

If it doesn't work come back to me and I'll make you a Video :)

**Comment by EvanWeeks** [comment]
_facepalm_ Well, that figures. They "disabled" it by moving it somewhere I wouldn't have thought to look.

Thanks! Seems to be working fine!

http://i.imgur.com/uFUyUoF.png

**Comment by Armitxes** [comment]
Glad to hear that.
If there is anything else feel free to ask.

/ Closed
