### ISSUE TITLE
Boolean values being highlighted as commands

### ISSUE THREAD

**Issue by jameslkingsley** [Armitxes/VSCode_SQF#12]
Sometimes a boolean value is highlighted yellow as appose to blue. I believe this is due to `true` and `false` being listed in `defg-key-statements` and `tuvw-key-statements`. After removing them, the issue was fixed.

**Comment by jameslkingsley** [comment]
`_isThereUnits = [false,true] select ((count _units) > 0)` - both bools are blue
`_isThereUnits = [false, true] select ((count _units) > 0)` - second bool (true) is yellow

**Comment by Armitxes** [comment]
Indeed, they are not meant to be in there. Thanks for the advice.

**Comment by Armitxes** [comment]
Fixed in latest release
