### ISSUE TITLE
Syntax highlighting broken at some point

### ISSUE THREAD

**Issue by SpazeGranade** [Armitxes/VSCode_SQF#14]
If i look at the attatched [File](https://github.com/Armitxes/VSCode_SQF/files/433427/file.txt) the highlighting works fine at the begining.
But from line 129 everything is just white. If i comment out line 123 it works up to line 144.

I cant figuere out why it does that.

![1276095244](https://cloud.githubusercontent.com/assets/16526698/17907609/097b4f4e-697d-11e6-94fb-00c66df4bf7d.png)

**Comment by Armitxes** [comment]
Confirmed, this is a new issue. Noticed it a few days ago.
Will see what I can do ;)

**Comment by Armitxes** [comment]
Alright, fix is in master. Will release it together with some other solved issues this week.

**Comment by Armitxes** [comment]
Fix released, update the extension inside VS Code.
