### ISSUE TITLE
While loop snippet brackets issue

### ISSUE THREAD

**Issue by ole1986** [Armitxes/VSCode_SQF#19]
Hi, great job with your extension

Just noted that the while loop snippet has the wrong brackets

```
while (condition) do {
	
};
```

shoudl become this:

```
while {condition} do {
	
};
```

**Comment by Armitxes** [comment]
Thanks for the bug report. Fixed within the next release

**Comment by Armitxes** [comment]
Resolved in https://github.com/Armitxes/VSCode_SQF/releases/tag/1.0.5
Marketplace update available is VS Code.

Thanks for the issue report.
