### ISSUE TITLE
private <array> marked as deprecated

### ISSUE THREAD

**Issue by Dorbedo** [Armitxes/VSCode_SQF#20]
`private <array>` shouldn't be marked as deprecated in arma 3.
A case, where it is usefull (defining variables on another scope):
```
private ["_myVar1", "_myVar2"];
switch (_switchvar) do {
    case 1: {_myVar1 = 1; _myVar2 = 1;};
    case 2: {_myVar1 = 2; _myVar2 = 2;};
    case 3: {_myVar1 = 3; _myVar2 = 3;};
    default {_myVar1 = 0; _myVar2 = 0;};
};
```

Or like in CBA, where you prevent variables from beeing overwritten:
https://github.com/CBATeam/CBA_A3/blob/7a1add1fc3f6227e5a10e329403d31138d5314cf/addons/settings/XEH_preInit.sqf#L45

**Comment by Armitxes** [comment]
Resolved in https://github.com/Armitxes/VSCode_SQF/releases/tag/1.0.5
Marketplace update available is VS Code.

Thanks for the issue report.
