### ISSUE TITLE
Multi-line string literals

### ISSUE THREAD

**Issue by ryanwoodcox** [Armitxes/VSCode_SQF#5]
Multi-line string literals lose their syntax highlighting. When breaking a string literal into multiple lines for readability the 'literal' highlighting goes away.

Example:
hint "hello this
     is two lines";

The "is two lines" starts to get regular code highlighting.

**Comment by Armitxes** [comment]
Thanks for the report, it has been fixed and was added to the branch for the next patch :+1:
