### ISSUE TITLE
Support EXT

### ISSUE THREAD

**Issue by jameslkingsley** [Armitxes/VSCode_SQF#6]
Currently the description.ext has no syntax highlighting. It should just be a simple config type of file which highlights the keys, values and classes. But it would be nice to see this added to this extension since it's related to Arma.

**Comment by jameslkingsley** [comment]
Just noticed it's possible to change the .ext type from plaint text to C++ by going to the bottom right of the editor.

**Comment by Armitxes** [comment]
Is this still a request? EXT File Support might be added since the VS Code doesn't recognize the file-extension automatically. Ever other ArmA Supported file extension (.hpp, .cpp) should be supported by VS Code by default. If not, you might wish to install an extension for it.

**Comment by jameslkingsley** [comment]
It would be nice but it's not necessary.
