### ISSUE TITLE
VsCode extension name

### ISSUE THREAD

**Issue by fda-odoo** [Armitxes/VSCode_SQF#68]
Hello,

I'm Florian, from the Odoo company. We are actually working on an extension for VsCode that we would like to publish on the Microsoft MarketPlace.
Unfortunately, according to Microsoft support, it seems that you already deployed an extension (but not publicly) that has the name Odoo. this extension lead us to your github https://github.com/Armitxes/VSCode_SQF
As you can imagine, we, as the official publisher, would like to be able to use our name to publish our extension. Would you agree to change your extension name and displayname in another name or unpublish it?
We would really appreciate it.

Thank you very much for your understanding

**Comment by Armitxes** [comment]
@fda-odoo Hi Florian, sure no problem. I'll contact you via email about it. Otherwise we can try to resolve it directly at the odoo experience at the ecodoo / ecoservice / Tec connect booth.
