### ISSUE TITLE
Case sensitive commands

### ISSUE THREAD

**Issue by jameslkingsley** [Armitxes/VSCode_SQF#7]
For example `foreach` is highlighted as white whereas `forEach` is highlighted blue. Commands should not be case sensitive in SQF.

**Comment by ryanwoodcox** [comment]
+1 vote for this feature as SQF is case INsensative.

**Comment by Armitxes** [comment]
Case sensitive code looks more beautiful and is easier to read ^^ I took the wiki as reference where they are very careful with case-sensivity in their code. AswelI I planned to link the commands to the wiki at some point (Ryan had a similar Idea for BIS Functions), and the URLs are case sensitive.

https://community.bistudio.com/wiki/foreach <- wrong
https://community.bistudio.com/wiki/forEach <- right

But in the end you're right, case-insensitive code works and shall be highlighted/supported. Will look into the issue.

**Comment by ryanwoodcox** [comment]
I agree - I personally always code using pascal case or camel case - but sadly the SQF language is case insensitive. Their wiki probably just has case sensitive routing that doesn't redirect properly to the correct documentation page.

**Comment by Armitxes** [comment]
Will be implemented in v0.5.0 the next days

**Comment by Armitxes** [comment]
Implemented in the v0.5 released a few minutes ago :+1: check for extension updates in VS Code.
