### ISSUE TITLE
code highlighting does not work properly

### ISSUE THREAD

**Issue by ole1986** [Armitxes/VSCode_SQF#8]
code lines, like spawn, compileFinal, compile and also some conditions and operators are not being highlighted

**Comment by ole1986** [comment]
my fault, forgot to select the color theme [SQF] Dark Theme

**Comment by Armitxes** [comment]
The issue with other themes is know, that's why I made the SQF Theme :)
Reported to Microsoft here: https://github.com/Microsoft/vscode/issues/2058
