### ISSUE TITLE
Highlight (alternative color) for _local, public variables

### ISSUE THREAD

**Issue by Falcata** [Armitxes/VSCode_SQF#9]
Right now the pluging dont highlight the public, _local variables inside the code and uses the same code color.

Using a other sqf plugins like notepad++ you have 2 alternative colors to see clearly when is created a _local variable and when is a public variable.

**Comment by Armitxes** [comment]
Will be implemented with the next update. Thanks for the advise.

**Comment by Armitxes** [comment]
Implemented in the v0.5 released a few minutes ago :+1: check for extension updates in VS Code.
